version: "3.3"
services:
  spark:
    build: dockerfiles/spark
    ports:
      - "7077:7077"
      - "8080:8080"
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - "./data:/data"
      - "./jars:/jars"
  zookeeper:
    build: dockerfiles/zookeeper
    ports:
      - "2181"
  kafka:
    build: dockerfiles/kafka
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "9092:9092"
    links: 
      - zookeeper
  hive:
    build: dockerfiles/hive
    command: ["tail", "-f", "/dev/null"]